### PR TITLE
Pin colored <1.5.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by shermansiu** [comment]
@Tobias-Fischer Out of curiosity, why was `colored` pinned to be below version 1.5.0?

**Comment by Tobias-Fischer** [comment]
There was a breaking API change: https://github.com/petercorke/robotics-toolbox-python/issues/384

The old API is still used: https://github.com/bdaiinstitute/spatialmath-python/blob/a29e647161662e202e79f51574c23d080e72ba5c/spatialmath/baseposematrix.py#L26

**Comment by shermansiu** [comment]
It was added back in version 2.1.1, although the docstring indicates that they will be deprecated.

https://gitlab.com/dslackw/colored/-/blob/2.1.1/colored/colored.py?ref_type=tags#L182-197

I suppose this should be fixed upstream regardless...

**Comment by shermansiu** [comment]
Upstream PR: https://github.com/bdaiinstitute/spatialmath-python/pull/173

**Pull request merged**
